enum VehicleType{
	BIKE,
	CAR,
	BUS,
	CONVOY,
	PARAGLIDER
};

struct Pos {
    string x;
	string y;
};

struct ObjectDetection{
    float detectionTime; 
    Pos detectionPos;
    float speed;
	VehicleType vehicleType;
	string licensePlate;
};
